
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox
import tkinter as tk
import sqlite3
import os
from registro import pagina
from homeFuncionario import HomeFunc

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\gugab\Documents\faculdade\4o Periodo\4ADS\2a try\AV2\Exercicios\ConBanco\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def exec_login(cursor):
    username_login = entry_User.get()
    senha_login = entry_Senha.get()

    resultado = verificar_cred(cursor, username_login, senha_login)

    if verificar_cred(cursor, username_login, senha_login):
        id_log = resultado[0]
        messagebox.showinfo("Login", "Login bem-sucedido!")
        HomeFunc(id_log)
    else:
        messagebox.showerror("Login", "Credenciais inválidas. Tente novamente.")



def verificar_cred(cursor, username, senha):
    try:
        cursor.execute("SELECT * FROM login WHERE username = ? AND senha = ?", (username, senha))
        resultado = cursor.fetchone()
        return resultado
    except sqlite3.Error as e:
        print("Erro ao executar a consulta:", e)
        return None

window = Tk()
window.title("Hotel Crudcabana")

conn = sqlite3.connect('crudcabana.db')
c = conn.cursor()

c.execute("""
    CREATE TABLE IF NOT EXISTS login (
        id_login INTEGER PRIMARY KEY,
        username TEXT,
        senha TEXT,
        permissao INTEGER
    )
""")

conn.commit()


window.geometry("700x400")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 400,
    width = 700,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    0.0,
    700.0,
    40.0,
    fill="#3379E2",
    outline="")

canvas.create_text(
    250.0,
    5.0,
    anchor="nw",
    text="Hotel Crudcabana",
    fill="#FFFFFF",
    font=("Inter Medium", 24 * -1)
)

canvas.create_rectangle(
    180.0,
    65.0,
    503.0,
    355.0,
    fill="#706D6D",
    outline="")

canvas.create_text(
    310.0,
    75.0,
    anchor="nw",
    text="Login",
    fill="#2E71D5",
    font=("Inter Bold", 24 * -1)
)

canvas.create_text(
    184.0,
    144.0,
    anchor="nw",
    text="Usuário:",
    fill="#FFFFFF",
    font=("Inter Bold", 14 * -1)
)

entry_User = tk.Entry(window, width=42)
entry_User.place(x=217, y=165)

canvas.create_text(
    184.0,
    191.0,
    anchor="nw",
    text="Senha",
    fill="#FFFFFF",
    font=("Inter Bold", 14 * -1)
)

entry_Senha = tk.Entry(window, width=42, show='*')
entry_Senha.place(x=217, y=213)

estilo_fonte = ("Inter Bold", 12, "bold")

btn_Login = tk.Button(window, width=12, text="Login", font=estilo_fonte, command=lambda: exec_login(c))
btn_Login.place(x=275, y=261)

estilo_Cadastro = ("Inter Bold", 10, "bold")

btn_Register = tk.Button(window, width=10, text="Cadastrar", font=estilo_Cadastro, command=pagina)
btn_Register.place(x=295, y=305)

window.resizable(False, False)
window.mainloop()
