
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import tkinter as tk
import sqlite3
from NovoAluguel import PaginaAlugar
from NovoQuarto import paginaQuarto
from NovoCliente import paginaRegistro
from ListarAluguel import ListaAluga
from ListarQuartos import ListaQuarto
from ListarClientes import ListaCliente

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\gugab\Documents\faculdade\4o Periodo\4ADS\2a try\AV2\Exercicios\tela Funcionários\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def receber_Nome(id_log):
    try:
        with sqlite3.connect('crudcabana.db') as conn:
            cursor = conn.cursor()
            cursor.execute("SELECT nome FROM pessoa WHERE id_login = ?", (id_log,))
            resultado = cursor.fetchone()
            if resultado:
                return resultado[0]  # Retorna o nome associado ao id_login
            else:
                return None
    except sqlite3.Error as e:
        print("Erro ao executar a consulta:", e)
        return None

estilo_Font = ("Inter Bold", 22, "bold")

def HomeFunc(id_log):
    window = Tk()

    window.title("Hotel CRUDcabana - HOME")

    conn = sqlite3.connect('crudcabana.db')
    c = conn.cursor()

    window.geometry("1080x720")
    window.configure(bg = "#FFFFFF")

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 720,
        width = 1080,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    #HEADER
    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        1080.0,
        83.0,
        fill="#3379E2",
        outline="")

    canvas.create_text(
        390.0,
        27.0,
        anchor="nw",
        text="Hotel Crudcabana",
        fill="#FFFFFF",
        font=("Inter Medium", 24 * -1)
    )

    nome_usuario = receber_Nome(id_log)
    canvas.create_text(
        884.0,
        28.0,
        anchor="nw",
        text=f"Olá, {nome_usuario}!",
        fill="#FFFFFF",
        font=("Inter Medium", 18 * -1)
    )

    #BACKGROUND
    canvas.create_rectangle(
        68.0,
        133.0,
        1032.0,
        664.0,
        fill="#706D6D",
        outline="")

    #HEAD HOME
    canvas.create_text(
        450.0,
        147.0,
        anchor="nw",
        text="Home Funcionários",
        fill="#2E71D5",
        font=("Inter Bold", 24 * -1)
    )

    #BG ALUGUEL
    canvas.create_rectangle(
        101.0,
        203.0,
        381.0,
        626.0,
        fill="#AAA049",
        outline="")

    #HEAD QUARTOS
    canvas.create_text(
        205.0,
        210.0,
        anchor="nw",
        text="Aluguéis",
        fill="#3F4146",
        font=("Inter Bold", 22 * -1)
    )

    canvas.create_line(111, 240, 371, 240, width=2, fill="black")

    #BTN Aluga
    btn_Alugar = tk.Button(window, width=12, height=2, text="Novo Aluguel", font=estilo_Font, bg='#CFCCB3', relief="raised", borderwidth=3, command=lambda: PaginaAlugar(c))
    btn_Alugar.place(x=129, y=280)

    canvas.create_line(200, 390, 300, 390, width=1, fill="black")
    canvas.create_line(220, 400, 280, 400, width=1, fill="black")
    canvas.create_line(240, 410, 260, 410, width=1, fill="black")

    #BTN ListAlug
    btn_ListAlug = tk.Button(window, width=12, height=2, text="Listar Aluguéis", font=estilo_Font, bg='#CFCCB3', relief="raised", borderwidth=3, command=ListaAluga)
    btn_ListAlug.place(x=129, y=450)

    canvas.create_line(200, 560, 300, 560, width=1, fill="black")
    canvas.create_line(220, 570, 280, 570, width=1, fill="black")
    canvas.create_line(240, 580, 260, 580, width=1, fill="black")

    #BG QUARTOS
    canvas.create_rectangle(
        410.0,
        203.0,
        690.0,
        626.0,
        fill="#B58A49",
        outline="")

    #HEAD QUARTOS
    canvas.create_text(
        505.0,
        210.0,
        anchor="nw",
        text="Quartos",
        fill="#3F4146",
        font=("Inter Bold", 22 * -1)
    )

    canvas.create_line(420, 240, 680, 240, width=2, fill="black")

    #BTN QUARTO
    btn_Quarto = tk.Button(window, width=12, height=2, text="Novo Quarto", font=estilo_Font, bg='#CFCCB3', relief="raised", borderwidth=3, command=lambda: paginaQuarto(c))
    btn_Quarto.place(x=437, y=280)

    canvas.create_line(508, 390, 608, 390, width=1, fill="black")
    canvas.create_line(528, 400, 588, 400, width=1, fill="black")
    canvas.create_line(548, 410, 568, 410, width=1, fill="black")

    btn_ListQuart = tk.Button(window, width=12, height=2, text="Listar Quartos", font=estilo_Font, bg='#CFCCB3', relief="raised", borderwidth=3, command=ListaQuarto)
    btn_ListQuart.place(x=437, y=450)

    canvas.create_line(508, 560, 608, 560, width=1, fill="black")
    canvas.create_line(528, 570, 588, 570, width=1, fill="black")
    canvas.create_line(548, 580, 568, 580, width=1, fill="black")

    #BG Clientes
    canvas.create_rectangle(
        719.0,
        203.0,
        999.0,
        626.0,
        fill="#507190",
        outline="")

    #HEAD Clientes
    canvas.create_text(
        805.0,
        210.0,
        anchor="nw",
        text="Clientes",
        fill="#3F4146",
        font=("Inter Bold", 22 * -1)
    )

    canvas.create_line(729, 240, 989, 240, width=2, fill="black")

    #BTN Clientes
    btn_Client = tk.Button(window, width=12, height=2, text="Novo Cliente", font=estilo_Font, bg='#CFCCB3', relief="raised", borderwidth=3, command=paginaRegistro)
    btn_Client.place(x=745, y=280)

    canvas.create_line(816, 560, 916, 560, width=1, fill="black")
    canvas.create_line(836, 570, 896, 570, width=1, fill="black")
    canvas.create_line(856, 580, 876, 580, width=1, fill="black")

    #BTN ListCliente
    btn_ListClient = tk.Button(window, width=12, height=2, text="Listar Clientes", font=estilo_Font, bg='#CFCCB3', relief="raised", borderwidth=3, command=ListaCliente)
    btn_ListClient.place(x=745, y=450)

    canvas.create_line(816, 390, 916, 390, width=1, fill="black")
    canvas.create_line(836, 400, 896, 400, width=1, fill="black")
    canvas.create_line(856, 410, 876, 410, width=1, fill="black")

    c.close()

    window.resizable(False, False)
    window.mainloop()
