
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox
from tkinter import ttk
import sqlite3


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\gugab\Documents\faculdade\4o Periodo\4ADS\2a try\AV2\Exercicios\Listar\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


def ListaQuarto():
    window = Tk()
    window.title("Hotel CRUDcabana - Listar Quartos")

    window.geometry("1080x720")
    window.configure(bg = "#FFFFFF")


    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 720,
        width = 1080,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        1080.0,
        83.0,
        fill="#3379E2",
        outline="")

    canvas.create_text(
        390.0,
        27.0,
        anchor="nw",
        text="Hotel Crudcabana",
        fill="#FFFFFF",
        font=("Inter Medium", 24 * -1)
    )

    canvas.create_rectangle(
        68.0,
        133.0,
        1032.0,
        664.0,
        fill="#706D6D",
        outline="")


    canvas.create_text(
        450.0,
        147.0,
        anchor="nw",
        text="Listar Quartos",
        fill="#2E71D5",
        font=("Inter Bold", 24 * -1)
    )

    #Tabela
    tblQuarto = ttk.Treeview(window)
    tblQuarto["columns"] = ("Id_quarto", "Nome_Quarto", "Capacidade", "Camas" , "Diaria")
    tblQuarto.heading("#0", text="ID")
    tblQuarto.heading("Id_quarto", text="ID")
    tblQuarto.heading("Nome_Quarto", text="Nome do Quarto")
    tblQuarto.heading("Capacidade", text="Capacidade do Quarto")
    tblQuarto.heading("Camas", text="Camas disponíveis")
    tblQuarto.heading("Diaria", text="Diaria")

    tblQuarto.column("#0", width=50)  # indice
    tblQuarto.column("Id_quarto", width=50)
    tblQuarto.column("Nome_Quarto", width=150)
    tblQuarto.column("Capacidade", width=150)
    tblQuarto.column("Camas", width=150)
    tblQuarto.column("Diaria", width=150)

    tblQuarto.place(x=130, y=236)

    # Limpar dados antigos
    for row in tblQuarto.get_children():
        tblQuarto.delete(row)

    # Conectar ao banco de dados
    with sqlite3.connect('crudcabana.db') as conn:
        cursor = conn.cursor()

    # Executar uma consulta SELECT
    cursor.execute("SELECT * FROM quarto")
    dados = cursor.fetchall()

    # Inserir dados na Treeview
    for dado in dados:
        # Adicionando os dados à Treeview
        tblQuarto.insert("", "end", values=dado)

    canvas.create_text(
        500.0,
        201.0,
        anchor="nw",
        text="Quartos",
        fill="#FFFFFF",
        font=("Inter Bold", 24 * -1)
    )
    window.resizable(False, False)
    window.mainloop()
