
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox
import tkinter as tk
import sqlite3


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\gugab\Documents\faculdade\4o Periodo\4ADS\2a try\AV2\Exercicios\Novo Quarto\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

entry_NomeQuarto = None
entry_Capacidade = None
entry_Camas = None
entry_Diaria = None

def criar_tabela():
    with sqlite3.connect('crudcabana.db') as conn:
        cursor = conn.cursor()
        cursor.execute("""CREATE TABLE IF NOT EXISTS quarto (
                Id_quarto INTEGER PRIMARY KEY AUTOINCREMENT,
                Nome_Quarto TEXT,
                Capacidade TEXT,
                Camas TEXT,
                Diaria TEXT
            )""")

def CriarQuarto():
    global entry_NomeQuarto, entry_Capacidade, entry_Camas, entry_Diaria

    NomeQuarto = entry_NomeQuarto.get()
    Capacidade = entry_Capacidade.get()
    Camas = entry_Camas.get()
    Diaria = entry_Diaria.get()

    try:
        with sqlite3.connect('crudcabana.db') as conn:
            cursor = conn.cursor()
        # SQL DE INSERT
        cursor.execute("INSERT INTO quarto VALUES (NULL, ?,?,?,?)", (NomeQuarto, Capacidade, Camas, Diaria))

        # ENVIANDO DADOS
        conn.commit()

        id_quarto = cursor.lastrowid
        # MENSAGEM DE SUCESSO
        messagebox.showinfo("Registro", "Quarto registrado com sucesso!")
        print("Quarto registrado com sucesso. ID do quarto:", id_quarto)

    except InterruptedError:
        messagebox.showerror("Erro", "Nome de quarto já existe. Escolha outro.")
        print("Erro: Nome de quarto já existe.")
    except sqlite3.Error as e:
        messagebox.showerror("Erro", f"Ocorreu um erro: {str(e)}")
        print("Erro desconhecido:", str(e))

def paginaQuarto(id_log):
    window = Tk()
    window.title("Hotel CRUDcabana - Novo Quarto")

    window.geometry("1080x720")
    window.configure(bg = "#FFFFFF")

    fonte= ("Inter Medium", 24 * -1)

    canvas = Canvas(
        window,
        bg = "#FFFFFF",
        height = 720,
        width = 1080,
        bd = 0,
        highlightthickness = 0,
        relief = "ridge"
    )

    canvas.place(x = 0, y = 0)
    canvas.create_rectangle(
        0.0,
        0.0,
        1080.0,
        83.0,
        fill="#3379E2",
        outline="")

    canvas.create_text(
        390.0,
        27.0,
        anchor="nw",
        text="Hotel Crudcabana",
        fill="#FFFFFF",
        font=("Inter Medium", 24 * -1)
    )

    canvas.create_rectangle(
        68.0,
        133.0,
        1032.0,
        664.0,
        fill="#706D6D",
        outline="")


    canvas.create_text(
        326.0,
        147.0,
        anchor="nw",
        text="Novo Aluguel",
        fill="#2E71D5",
        font=("Inter Bold", 24 * -1)
    )

    canvas.create_text(
        884.0,
        25.0,
        anchor="nw",
        text="Nomecliente",
        fill="#FFFFFF",
        font=("Inter Medium", 24 * -1)
    )

    #Entry Nome Quarto
    canvas.create_text(
        103.0,
        204.0,
        anchor="nw",
        text="Nome Do Quarto",
        fill="#FFFFFF",
        font=("Inter Bold", 24 * -1)
    )

    entry_NomeQuarto = tk.Entry(window, width=61, font=fonte)
    entry_NomeQuarto.place(x=103, y=237)

    #Entry Capacidade
    canvas.create_text(
        104.0,
        302.0,
        anchor="nw",
        text="Capacidade",
        fill="#FFFFFF",
        font=("Inter Bold", 24 * -1)
    )

    entry_Capacidade = tk.Entry(window, width=19, font=fonte)
    entry_Capacidade.place(x=103, y=335)

    #Entry Camas
    canvas.create_text(
        103.0,
        399.0,
        anchor="nw",
        text="Camas",
        fill="#FFFFFF",
        font=("Inter Bold", 24 * -1)
    )

    entry_Camas = tk.Entry(window, width=9, font=fonte)
    entry_Camas.place(x=103, y=433)

    #Entry diaria
    canvas.create_text(
        103.0,
        492.0,
        anchor="nw",
        text="Diária",
        fill="#FFFFFF",
        font=("Inter Bold", 24 * -1)
    )
    entry_Diaria = tk.Entry(window, width=11, font=fonte)
    entry_Diaria.place(x=103, y=526)

    canvas.create_rectangle(
        103.0,
        526.0,
        252.0,
        560.0,
        fill="#D9D9D9",
        outline="")

    #CRIANDO TABELAS
    criar_tabela()

    #Btn Cadastrar
    estilo_Cadastro = ("Inter Bold", 12, "bold")
    btn_Criar = tk.Button(window, width=21, height=2, text="Cadastrar", font=estilo_Cadastro, command=CriarQuarto)
    btn_Criar.place(x=698, y=534)

    window.resizable(False, False)
    window.mainloop()
